### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BlazeWasHere** [BlazeWasHere/motor-sqlite#1]
- [x] Delete
- [x] Insert
- [x] count_documents

**Comment by FluxedScript** [comment]
- [ ] find_one_and_replace
- [ ] find_one_and_delete
- [ ] find_one_and_update
- [ ] delete_many
- [ ] update_many
- [ ] replace_one
- [ ] insert_many
- [ ] drop_collection

**Comment by FluxedScript** [comment]
- [ ] use raw sql option like posts.execute_raw("SELECT * FROM....")
